apiVersion: apps/v1
kind: Deployment
metadata:
  name: humoq-be-deployment2
  labels:
    uri: api2.humoq.com
spec:
  selector:
    matchLabels:
      app: humoq-be2
      uri: api2.humoq.com
  replicas: 1
  template:
    metadata:
      labels:
        app: humoq-be2
        uri: api.humoq.com
    spec:
      containers:
        - name: humoq-be2
          image: humoq/humoq-be2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: humoq-be-service2
spec:
  selector:
    app: humoq-be2
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      nodePort: 30003
      port: 80
      targetPort: 8002
